<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

In [2]:
import numpy as np

# Exercise 1 (Total Recall)

| **Term** 	| **Brief Description** 	|
|:---	|:---	|
| Subsetting 	| Selecting elements 	|
| Indexing 	| Selecting one element 	|
| Slicing 	| Selecting a range of elements 	|
| Masking 	| Use masking to filter True/False items 	|

# Exercise 2

In [4]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [7]:
x = np_array_2d

In [12]:
x[:,0]

array(['1', '3', '2', '4', '5', '7', '6', '8', '10', '9'], dtype='<U11')

In [15]:
y = np.array(['1', '3', '2', '4', '5', '7', '6', '8', '10', '9'])

In [16]:
y.astype(int)

array([ 1,  3,  2,  4,  5,  7,  6,  8, 10,  9])

In [19]:
y.astype(int) % 2

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1], dtype=int32)

In [29]:
mask = (y.astype(int)%2) == 1
mask

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

In [30]:
y[mask]

array(['1', '3', '5', '7', '9'], dtype='<U2')