<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

In [2]:
import numpy as np

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

In [5]:
py_s_names = ["BW", "IM", "DS"]
py_r_names = ["Natasha", "Tony", "Stephen"]

In [6]:
np_s_names = np.array(["BW", "IM", "DS"])
np_r_names = np.array(["Natasha", "Tony", "Stephen"])

In [7]:
superhero_info = {
    "Natasha": "BW",
    "Tony": "IM",
    "Stephen": "DS"
}

## 1.2 Accessing data from a list (or array)

In [8]:
py_s_names = ["BW", "IM", "DS"]
py_r_names = ["Natasha", "Tony", "Stephen"]

In [11]:
py_s_names[2]

'DS'

In [17]:
py_s_names[-3]

'BW'

## 1.3 Accessing data from a dictionary

In [20]:
superhero_info = {
    "Natasha": "BW",
    "Tony": "IM",
    "Stephen": "DS"
}

In [23]:
superhero_info["Tony"]

'IM'

In [24]:
superhero_info.keys()

dict_keys(['Natasha', 'Tony', 'Stephen'])

## 1.4 Higher dimensional lists

In [25]:
py_info_2d = [['Test1','Test2'],
             ['Test1','Test2']]

# 2 Lists vs. Arrays

## 2.1 Size

In [27]:
py_info_2d = [['Test1','Test2'],
             ['Test1','Test2']]
np_array_2d = np.array(py_info_2d)

In [29]:
len(py_info_2d)

2

In [30]:
len(np_array_2d)

2

In [31]:
np_array_2d.shape

(2, 2)

## 2.2 Arrays are fussy about type

In [34]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

In [35]:
py_list

[1, 1.5, 'A']

In [36]:
np_array

array(['1', '1.5', 'A'], dtype='<U32')

## 2.3 Adding a number

In [38]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [40]:
np_array + 10

array([11, 12, 13, 14, 15])

In [41]:
py_list + 10

TypeError: can only concatenate list (not "int") to list

## 2.4 Adding another list

In [42]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [43]:
py_list_1 + py_list_2

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [44]:
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a Number

In [45]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [46]:
py_list * 2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [47]:
np_array * 2

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

In [4]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)
np_array ** 2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [ ]:
# Why is there a dtype=int32 ?

## 2.7 Asking questions

In [5]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [9]:
py_list == [1,2,3,4,5]

True

In [10]:
# py_list == 3 os asking if the list is exactly as written

In [11]:
np_array == 3

array([False, False,  True, False, False])

In [13]:
np_array > 3

array([False, False, False,  True,  True])

In [12]:
#np_array == 3 is asking if each element in the array is equal to 3

## 2.8 Mathematics

In [14]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [15]:
sum(py_list)

15

In [16]:
np_array.sum()

15

In [17]:
np_array.mean()

3.0

# Exercises & Self-Assessment

In [ ]:



# Your solution here




## Footnotes