<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

In [2]:
import numpy as np

# 1 Subsetting: Indexing and Slicing

Subsetting - Select<br>
Indexing - Select one element<br>
Slicing - Select a range of elements

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [4]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

x = py_list

In [5]:
x[0]

'a1'

In [6]:
x[0:3]

['a1', 'b2', 'c3']

In [9]:
x[1:8:2]

['b2', 'd4', 'f6', 'h8']

In [11]:
x[::-1]

['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1']

## 1.2 Arrays only | Subsetting by masking

In [13]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
my_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [14]:
np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [15]:
np_array[np_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [18]:
np_array[~(np_array > 3)]

array([1, 2, 3])

In [20]:
np_array[(np_array > 3) & (np_array < 8)]

array([4, 5, 6, 7])

In [21]:
np_array[(np_array < 3) | (np_array > 8)]

array([ 1,  2,  9, 10])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [22]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [23]:
np_array_2d[3]

array(['4', 'D'], dtype='<U11')

In [27]:
py_list_2d[3][1]

'D'

In [29]:
np_array_2d[:3, 0]

array(['1', '2', '3'], dtype='<U11')

In [30]:
py_list_2d[3:6][0]

[4, 'D']

In [31]:
np_array_2d[3:6, 0]

array(['4', '5', '6'], dtype='<U11')

In [32]:
np_array_2d[:, 0]

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U11')

## 1.4 Growing lists

In [33]:
x=[1, 2]*5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [34]:
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
x

[1, 2, 3, 4]

In [37]:
x=[1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

In [39]:
x=[1, 2, 3]
x.append([4, 5, 6])
x

[1, 2, 3, [4, 5, 6]]

In [40]:
x=[1, 2, 3]
x.extend([4, 5, 6])
x

[1, 2, 3, 4, 5, 6]

# Some loose ends

## 1.5 Tuples

In [41]:
a=(4,5,6)

In [42]:
print(a)

(4, 5, 6)


In [44]:
print(a[2])

6


In [45]:
a[0]=2

TypeError: 'tuple' object does not support item assignment

## 1.6 Be VERY careful when copying

In [46]:
x=[1, 2, 3]
y=x.copy()
z=x.copy()

In [47]:
y

[1, 2, 3]

In [48]:
z

[1, 2, 3]

# Exercises & Self-Assessment

In [ ]:



# Your solution here




## Footnotes